<%@ Page Title="Airborne Remote Sensing Platform" Language="C#" MasterPageFile="~/Page.Master" AutoEventWireup="true" CodeBehind="PageARSP.aspx.cs" Inherits="SMCRI.WebSite.PageARSP" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="BodyContent" runat="server">
    <div class="col s12 m6">
        <div class="card grey lighten-1">
            <div class="card-content black-text">
                <div class="carousel carousel-slider">
                    <a class="carousel-item" href="#one!">
                        <img src="/Images/Airborne Remote sensing_1.jpg" /></a>
                    <a class="carousel-item" href="#two!">
                        <img src="/Images/Airborne Remote Sensing_3.jpg"></a>
                </div>
            </div>
        </div>
    </div>
    <div class="col s12 m6">
        <div class="card grey lighten-1">
            <div class="card-content black-text">
                <span class="card-title"><h4>Airborne Remote Sensing Platform</h4><img src="/Images/NRF-SAEON LOGO.jpg" class="card-logo right" /></span>
                <p>
                    The SMCRI has acquired a single engine,
                        high wing light aircraft equipped with
                        complex and integrated sensory
                        equipment for the purposes of conducting
                        aerial surveys where accurate, georeferenced
                        high definition (HD) imagery are
                        required for scientific purposes. The aircraft
                        is a Glasair Sportsman, a modern design from
                        the USA that offers exceptional performance
                        capabilities for its class and is affordable to
                        operate as it runs on automotive fuel (mogas)
                        as opposed to aviation fuel (avgas). With
                        6 hours endurance and a cruise speed of
                        135 knots it allows for vast distances to be
                        covered without refuelling.
                </p>
                <p>
                    <br />
                </p>
                <p>
                    The sensory pack is setup over open
                        viewports in the fuselage floor which
                        allows for the continuous capture of high
                        quality overlapped, horizontal images. High
                        definition, geo-referenced orthomosaics can
                        be generated from these images using state
                        Airborne Remote
                        Sensing Platform
                        of the art post-processing software which
                        corrects for angle distortions and drift by
                        using information generated by the Inertial
                        Measurement Unit (IMU) at the time of each
                        image’s capture. These surveys will be used
                        mainly to document and monitor changes in
                        vegetation, dune and shoreline migration,
                        estuary mouth states and episodic events
                        (e.g. Harmful Algal Blooms, oil spills, etc)
                        along the entire coastline of South Africa.
                        The initial sensor installation also allows for
                        the capture of thermal Infra-Red (IR) images
                        that are useful for mapping surface spatial
                        temperature patterns. The intention is for
                        both a hyperspectral sensor and LiDAR
                        (Light Detection and Ranging) to be installed
                        at a later stage to enable the platform to
                        accurately measure the reflectance of
                        the landscape/ocean as well as generate
                        precise, three-dimensional information
                        about the shape of the Earth and its surface
                        characteristics down to a depth of 30 m.
                </p>
            </div>
        </div>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ScriptContent" runat="server">
    <script type="text/javascript">
        $('.carousel').carousel({
            fullWidth: true,
            indicators: true
        });
        function autoplay() {
            $('.carousel').carousel('next');
            setTimeout(autoplay, 2000);
        }
        setTimeout(autoplay, 2000);
    </script>
</asp:Content>
